import 'dart:io';
import 'package:path/path.dart' as p;

/// 为 lib/tools/*.txt 生成对应的 *.g.dart。
///
/// 用法：
///   dart run tool/generate_tool_descriptions.dart
///
/// 生成规则：
/// - 输入：lib/tools/xxx_tool.txt
/// - 输出：lib/tools/xxx_tool.g.dart
/// - 导出常量名：xxxToolDescription（驼峰命名）
void main() {
  final root = Directory.current.path;
  final toolsDir = Directory(p.join(root, 'lib', 'tools'));
  if (!toolsDir.existsSync()) {
    stderr.writeln('未找到工具目录：${toolsDir.path}');
    exit(1);
  }

  final txtFiles = toolsDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.txt'))
      .toList();

  if (txtFiles.isEmpty) {
    print('未找到 .txt 工具描述文件，跳过生成。');
    return;
  }

  var generatedCount = 0;
  for (final txtFile in txtFiles) {
    final basename = p.basenameWithoutExtension(
      txtFile.path,
    ); // e.g. task_plan_tool
    final outputName = '$basename.g.dart';
    final outputPath = p.join(toolsDir.path, outputName);

    final content = txtFile.readAsStringSync();
    final constName = _toCamelCase(basename) + 'Description';

    final buf = StringBuffer();
    buf.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buf.writeln('// Generated by tool/generate_tool_descriptions.dart');
    buf.writeln();
    buf.writeln('/// Tool description for `$basename`.');
    buf.writeln("const String $constName = r'''");
    buf.write(content);
    // Ensure the raw string ends cleanly; trailing newline inside txt is preserved.
    if (!content.endsWith('\n')) {
      buf.writeln();
    }
    buf.writeln("'''");
    buf.writeln(';');

    File(outputPath).writeAsStringSync(buf.toString());
    generatedCount++;
    print('Generated: lib/tools/$outputName');
  }

  print('完成，共生成 $generatedCount 个文件。');
}

String _toCamelCase(String snakeCase) {
  return snakeCase
      .split('_')
      .map(
        (word) =>
            word.isEmpty ? '' : '${word[0].toUpperCase()}${word.substring(1)}',
      )
      .join('')
      .replaceFirstMapped(RegExp(r'^[A-Z]'), (m) => m.group(0)!.toLowerCase());
}
