// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `agnes_video_tool`.
const String agnesVideoToolDescription = r'''
用户让你生成一段短视频的时候用它。需要给出视频内容的描述。生成需要一点点时间，完成后会给用户播放预览。
'''
;
