// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `ai_daily_tool`.
const String aiDailyToolDescription = r'''
用户让你生成一份 AI 日报——汇总某个主题的最新资讯和动态时用它。会主动搜索、筛选、组织成一份结构化的日报。讲清楚要什么主题和时间范围就好。
'''
;
