// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `ask_user_tool`.
const String askUserToolDescription = r'''
你遇到一个需要用户做决定的事，但你没有足够的信息——比如"要不要删？""用哪个版本？"——就用它去问 ta。把问题和选项讲清楚，让 ta 选。不要替用户做决定。
'''
;
