// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_back_tool`.
const String browserBackToolDescription = r'''
浏览器后退到上一页。
'''
;
