// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_get_page_info_tool`.
const String browserGetPageInfoToolDescription = r'''
获取当前页面的结构化信息：标题、URL、加载状态、滚动位置、页面总高度、视口尺寸、元素总数。用于判断"页面是否加载完""还能往下滚多少""当前在哪个页面"。
'''
;
