// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_wait_tool`.
const String browserWaitToolDescription = r'''
等待页面就绪。两种用法：1) 仅传 ms（毫秒）做固定等待（默认 1000），用于导航后等加载；2) 传 selector（CSS 选择器）+ ms（最长等待），轮询直到该元素出现再返回，避免"页面没加载完就操作"。
'''
;
