// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_search_tool`.
const String browserSearchToolDescription = r'''
在浏览器中直接搜索关键词（无需自己拼 URL）。engine 可选 bing（默认）/ google / duckduckgo / baidu。打开搜索结果页后，用 browser_snapshot 或 browser_get_text 读取结果。
'''
;
