// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_open_tool`.
const String browserOpenToolDescription = r'''
打开指定 URL 并返回页面快照（标题 + 正文摘要 + 所有可交互元素的 ref 列表）。若浏览器会话不存在则自动创建。后续可用 browser_snapshot 刷新快照、browser_click 点击元素返回到新页面。
'''
;
