// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_snapshot_tool`.
const String browserSnapshotToolDescription = r'''
获取当前页面的结构化快照：标题、正文文本（前 3000 字）、所有可交互元素（a/button/input 等）的 ref 与位置。常用于 navigation 或 click 后查看页面变化。
'''
;
