// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_get_readable_tool`.
const String browserGetReadableToolDescription = r'''
提取页面正文：自动去除导航/页脚/脚本/广告等噪声，优先取 article/main/[role=main]，返回干净的纯文本，适合读长文、博客、文档。支持 offset/max_length 分页（默认 6000 字符）。若内容很长，请用 offset 续读。
'''
;
