// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_close_tool`.
const String browserCloseToolDescription = r'''
关闭浏览器当前页面（清空 WebView）。
'''
;
