// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_goto_tool`.
const String browserGotoToolDescription = r'''
让内置浏览器打开指定网址。参数 url 为目标链接（含 http/https）。打开后建议先调用 browser_wait 等待页面加载（约 800-1500ms），再用 browser_snapshot 获取可交互元素、或用 browser_get_text/browser_get_readable 读取页面正文。
'''
;
