// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_set_user_agent_tool`.
const String browserSetUserAgentToolDescription = r'''
设置浏览器 User-Agent（UA）。传入具体 UA 字符串可伪装成移动端/特定浏览器；传空字符串恢复默认桌面 UA。修改后建议重新 browser_goto 目标页以使其生效。
'''
;
