// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_scroll_tool`.
const String browserScrollToolDescription = r'''
按像素值移动当前页面滚动条。正数向下滚动以露出下方更多内容、负数向上。默认移动 300px。
'''
;
