// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_evaluate_tool`.
const String browserEvaluateToolDescription = r'''
在当前页面执行任意 JavaScript 代码并返回执行结果。适用于提取 browser_snapshot 未覆盖的页面数据。
'''
;
