// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_wait_tool`.
const String browserWaitToolDescription = r'''
等待页面就绪。三种用法：1) 仅传 ms（毫秒）做固定等待（默认 1000）；2) 传 selector（CSS 选择器）+ ms，轮询等待元素出现；3) 传 dom_stable: true（推荐 React/Vue SPA 页面，建议 ms=3000-5000），轮询 body.innerHTML 长度连续相同即认为页面渲染完成。SPA 页面导航后务必先用本工具 dom_stable 模式等待客户端渲染完成，否则 snapshot/get_text 可能返回空。
'''
;
