// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_fill_form_tool`.
const String browserFillFormToolDescription = r'''
批量填充表单字段，fields 为 [{ref, text}, ...]。提交请用 browser_click 点击提交按钮。
'''
;
