// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_screenshot_tool`.
const String browserScreenshotToolDescription = r'''
截取当前页面的完整截图，返回 base64 编码的 PNG 图片。截图大小可能很大，AI 应仅描述截图内容而非直接输出 base64 字符串。
'''
;
