// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_type_tool`.
const String browserTypeToolDescription = r'''
向输入框填入文本并触发 input/change 事件。需提供 CSS 选择器定位输入框（从 browser_snapshot 的元素列表获取 ref）。
'''
;
