// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_select_tool`.
const String browserSelectToolDescription = r'''
在 browser_snapshot 返回的 select 元素 ref 中选择选项（按 value 或显示文本匹配）。可选传 cssPath（来自 snapshot 的 cssPath 字段），当 React 重渲染导致 ref 失效时，会自动用 cssPath 重新查找。选择成功后自动触发 change 事件。
'''
;
