// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_type_tool`.
const String browserTypeToolDescription = r'''
在 browser_snapshot 返回的 ref 输入框中输入文本（兼容 React/Vue 受控组件——使用原生 value setter + focus + input/change 事件）。如需提交，输入后调用 browser_press_key(ref, "Enter") 或 browser_click 提交按钮。
'''
;
