// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_get_cookies_tool`.
const String browserGetCookiesToolDescription = r'''
读取当前页面（或指定 url）的 Cookie 字符串。可用于查看/保存登录态。
'''
;
