// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_close_tool`.
const String browserCloseToolDescription = r'''
关闭当前浏览器会话并释放 WebView 内存。关闭后再次使用 browser_open 会自动重建会话。
'''
;
