// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_get_text_tool`.
const String browserGetTextToolDescription = r'''
读取当前页面可见纯文本（document.body.innerText），适合"读懂页面内容""提取文章正文"。单次默认最多返回 6000 字符；若页面更长，工具会自动提示剩余字符数，请用 offset 参数分多次读取以获取完整内容（例如 offset=6000）。无需自己写 JS。
'''
;
