// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `browser_scroll_tool`.
const String browserScrollToolDescription = r'''
滚动浏览器页面。delta_x/delta_y 为相对像素（默认向下滚 300）。长页面操作前先用本工具滚到目标区域，再 browser_snapshot 获取该区域元素。返回滚动后的位置与是否到底。
'''
;
