// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `calendar_tool`.
const String calendarToolDescription = r'''
读写系统日历：查看日程、创建事件、删除事件。当用户提到"日程"、"会议"、"约会"、"提醒我明天..."或需要添加到日历时使用。
'''
;
