// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `calendar_query_tool`.
const String calendarQueryToolDescription = r'''
想知道用户最近有什么安排的时候用它。可以查某一天的日程，也可以查一段时间内的。默认查昨天到未来一周——这样你能帮 ta 看看"明天有什么事"或"这周还有什么空档"。
'''
;
