// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `calendar_delete_tool`.
const String calendarDeleteToolDescription = r'''
用户说某条日程取消了、不去了，你就用它来删掉。需要提供日程的 id，这个 id 可以从 calendar_query 的返回结果里拿到。
'''
;
