// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `calendar_add_tool`.
const String calendarAddToolDescription = r'''
添加一条日历日程（事件标题必填）。
'''
;
