// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `calendar_delete_tool`.
const String calendarDeleteToolDescription = r'''
按事件 ID 删除一条日历日程。
'''
;
