// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `calendar_query_tool`.
const String calendarQueryToolDescription = r'''
查询一段时间内的日历日程。可指定 date/time 或 start_ms/end_ms，默认查昨天到 7 天后。
'''
;
