// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `context_doc_update_tool`.
const String contextDocUpdateToolDescription = r'''
覆盖写入上下文文档（先 context_doc_read 获取全文，整合后整篇覆盖）。agent 文档写入需设置 reviewed=true，避免覆盖 SOUL 人格设定。
'''
;
