// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `context_doc_read_tool`.
const String contextDocReadToolDescription = r'''
读取上下文文档全文：soul=人格设定、user=用户资料、agent=任务经验、memory=长期记忆、knowledge=知识库（knowledge 需额外 filename）。
'''
;
