// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `create_rich_note_tool`.
const String createRichNoteToolDescription = r'''
用户说要记一篇带格式、带图片的笔记时用它——比 save_note 更丰富。支持 Markdown 排版，可以插入 base64 图片。写完告诉 ta"笔记已保存"然后问要不要预览。
'''
;
