// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `deep_search_tool`.
const String deepSearchToolDescription = r'''
深度搜索（Deep Search）：针对一个复杂、需要多方查证的问题，自动将其拆解为若干子问题，多轮调用搜索引擎（SearXNG / Tavily）并精读相关网页正文，最后综合出一份带引用的结构化答案。

适用场景：
- 需要横向对比、查证事实、汇总多个信息来源的深度调研
- 普通搜索结果不够全面，希望一次拿到有组织、有出处的综述

不适用：简单的事实查询（直接用 web_fetch 或搜索工具即可）。

注意：本工具会发起多次网络请求，耗时较长，请仅在确实需要深度调研时使用。
''';
