// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `deep_search_tool`.
const String deepSearchToolDescription = r'''
当一个简单的搜索结果不够深入时用它。它会自动拆解你的问题，分多个子问题分别搜索，然后汇总出一份比较全面的答案——适合那种需要了解来龙去脉的问题。比单次搜索慢一些，但查得更透彻。
'''
;
