// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `defer_execute_tool`.
const String deferExecuteToolDescription = r'''
你通过 tool_search 找到了一个工具，现在要真正调用它的时候用它。tool_search 只是"看看有什么"，这个才是"真的去做"。把 tool_search 返回的名字和参数填进去就行。
'''
;
