// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `defer_execute_tool`.
const String deferExecuteToolDescription = r'''
调用通过 tool_search 发现的延迟工具。你必须先调用 tool_search 确认目标工具存在及其参数，再使用此工具执行。
'''
;
