// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `file_tool`.
const String fileToolDescription = r'''
管理应用本地文件：列目录、读写文件、创建文件夹、删除。当用户明确提到"文件"、"文档"、"保存到本地"或给你文件路径时使用。
'''
;
