// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `fs_ls_tool`.
const String fsLsToolDescription = r'''
列出虚拟文件系统中某目录的内容（目录/文件）。
'''
;
