// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `fs_mkdir_tool`.
const String fsMkdirToolDescription = r'''
你需要创建一个新目录的时候用它。比如想在一个目录下面建一个子文件夹来整理文件。
'''
;
