// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `fs_mkdir_tool`.
const String fsMkdirToolDescription = r'''
在虚拟文件系统中创建目录。
'''
;
