// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `fs_rm_tool`.
const String fsRmToolDescription = r'''
你需要删除某个文件的时候用它。删之前确认一下确实要删——文件删了就没法恢复了。
'''
;
