// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `fs_read_tool`.
const String fsReadToolDescription = r'''
你需要读取某个文件的全部内容时用它。拿到文件路径后，它会返回文件里写了什么。读之前最好先用 fs_ls 确认一下文件确实存在。
'''
;
