// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `fs_read_tool`.
const String fsReadToolDescription = r'''
读取虚拟文件系统中某文件的完整内容。
'''
;
