// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `fs_walk_tool`.
const String fsWalkToolDescription = r'''
你需要把一个目录里所有文件（包括子目录里的）全部列出来时用它。比 fs_ls 更深——适合要遍历整个目录树的时候。
'''
;
