// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `fs_write_tool`.
const String fsWriteToolDescription = r'''
向虚拟文件系统中写入文件（覆盖式）。
'''
;
