// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `fs_walk_tool`.
const String fsWalkToolDescription = r'''
递归列出虚拟文件系统中某目录下的所有文件路径。
'''
;
