// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `location_tool`.
const String locationToolDescription = r'''
需要知道用户现在在哪个城市的时候用它。比如查天气要地点、搜周边要定位——先拿到位置再做下一步。
'''
;
