// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `manage_note_tool`.
const String manageNoteToolDescription = r'''
管理已有笔记：列出列表、读取正文、修改内容、删除笔记。
当用户要求查看笔记列表、阅读某条笔记的完整内容、修改某条笔记、删除笔记时使用本工具。
操作笔记前，建议先 list 获取准确的 note_id，再按 id 执行 read/update/delete。
注意：新建笔记请用 save_note 工具，本工具不负责新建。
''';
