// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `notes_update_tool`.
const String notesUpdateToolDescription = r'''
修改某条笔记的标题与正文（支持 Markdown）。
'''
;
