// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `notes_update_tool`.
const String notesUpdateToolDescription = r'''
用户说要修改某一篇笔记的时候用它。告诉 ta 现在的笔记 id 和要改的内容（标题或正文），改完告诉 ta 一声。先读再改，别覆盖掉 ta 没说要改的部分。
'''
;
