// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `notes_list_tool`.
const String notesListToolDescription = r'''
列出当前全部笔记（id + 标题 + 摘要）。先调用本工具获取笔记 id，再用于 notes_read / notes_update / notes_delete。
'''
;
