// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `notes_delete_tool`.
const String notesDeleteToolDescription = r'''
删除某条笔记（提供 note_id）。
'''
;
