// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `notes_read_tool`.
const String notesReadToolDescription = r'''
读取某条笔记的完整正文与元数据。
'''
;
