// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `plan_verify_tool`.
const String planVerifyToolDescription = r'''
计划里所有任务都标完 done/failed 后，用它来最终校验——确认没有遗漏、没有卡住的步骤。校验通过才能说"完成了"。这是给自己的最后一道保险：每件事都清清楚楚地了结，不留尾巴。
'''
;
