// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `plan_verify_tool`.
const String planVerifyToolDescription = r'''
校验所有任务是否已完成/失败；通过后才能输出最终答案。
'''
;
