// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `plan_clear_tool`.
const String planClearToolDescription = r'''
清除当前计划。需先 plan_verify 校验通过后才能清除。
'''
;
