// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `plan_status_tool`.
const String planStatusToolDescription = r'''
查看当前任务计划的进度摘要（已完成/剩余步骤）。
'''
;
