// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `plan_create_tool`.
const String planCreateToolDescription = r'''
创建任务计划：提供 title 与 tasks（支持 parent 构建子任务树、dependsOn 指定依赖）。创建后自动将第一个可执行任务设为进行中。
'''
;
