// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `plan_update_tool`.
const String planUpdateToolDescription = r'''
更新某个任务的状态。需提供 task_id 与 status；blocked/failed 建议填写原因。
'''
;
