// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `plan_clear_tool`.
const String planClearToolDescription = r'''
任务全部搞定之后，用它把计划清空。清之前需要先用 plan_verify 确认所有任务都已通过，防止不小心删了还没做完的计划。
'''
;
