// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `plan_advance_tool`.
const String planAdvanceToolDescription = r'''
自动将当前 in_progress 任务标记为 done，并推进到下一个可执行任务。
'''
;
