// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `reminder_tool`.
const String reminderToolDescription = r'''
用户让你在某个时间提醒 ta 做什么事的时候用它。比如"十分钟后提醒我喝水"或"明天下午三点提醒我开会"。设置好之后告诉用户一声"已记下"就行。闹钟到了会推通知到手机上。
'''
;
