// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `reminder_tool`.
const String reminderToolDescription = r'''
创建定时提醒，到时间会推送系统通知。当用户说"提醒我..."、"N分钟后叫我"、"定时提醒"时使用。
''';
