// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `save_note_tool`.
const String saveNoteToolDescription = r'''
用户说要"记下来"或"保存"某段内容时用它。简单笔记就存纯文本，保存完告诉用户一声就好。
'''
;
