// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `save_note_tool`.
const String saveNoteToolDescription = r'''
将内容保存为笔记。支持 Markdown 格式和图片插入。
'''
;
