// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `skill_manage_tool`.
const String skillManageToolDescription = r'''
管理 Agent 技能包。技能包是一组相关工具和 prompt 模板的组合。
- list: 查看所有可用技能
- activate: 激活一个技能（加载其工具和 prompt）
- deactivate: 停用一个技能
- match: 根据用户输入自动匹配可能需要的技能
激活技能后，对应的工具和 prompt 模板会自动加载到当前会话中。
''';
