// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `skill_read_tool`.
const String skillReadToolDescription = r'''
读取某个 Skill 的详细指令正文（SKILL.md）。
'''
;
