// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `skill_match_tool`.
const String skillMatchToolDescription = r'''
用户跟你说了一段需求，你需要找到最匹配的 Skill 时用它。它会根据关键词和语义匹配出最合适的 Skill。拿到结果后再用 skill_read 细看。
'''
;
