// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `skill_list_tool`.
const String skillListToolDescription = r'''
列出所有可用 Skill 的目录（name + description）。
'''
;
