// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `skill_read_tool`.
const String skillReadToolDescription = r'''
你看到一个 Skill 的描述觉得可能有用，需要读它的完整指令时用它。Skill 里面会写清楚具体的执行步骤和注意事项——读了再照着做，别瞎猜。
'''
;
