// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `skill_list_tool`.
const String skillListToolDescription = r'''
你需要看看当前有哪些 Skill 可以用的时候用它。会列出所有 Skill 的名字和简短描述——就像翻看一本技能目录，看看有没有哪个能帮上忙。
'''
;
