// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `skill_match_tool`.
const String skillMatchToolDescription = r'''
根据用户输入文本，按关键词匹配最相关的 Skill。
'''
;
