// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `skill_create_tool`.
const String skillCreateToolDescription = r'''
创建新技能：需提供 name、description（触发场景）、instructions（执行步骤与可用工具）。
'''
;
