// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `skill_read_cookbook_tool`.
const String skillReadCookbookToolDescription = r'''
读取某个 Skill 的 cookbook 详细步骤文件。
'''
;
