// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `task_plan_tool`.
const String taskPlanToolDescription = r'''
管理当前任务的执行计划。当你要完成一个多步骤的复杂任务时使用，例如：搜索+整理+保存、多轮搜索对比、创建多个文件、多步骤分析等。
先调用 create 创建计划并列出所有步骤，create 会自动将第一个可执行任务设为 in_progress。
创建时可指定 dependsOn 字段表达任务间依赖（被依赖的任务必须 done 后才能开始本任务）。
任务状态必须按轮次串行推进，每轮最多只能发起一次 task_plan 状态变更：
- 开始后续任务前调用 update 将其设为 in_progress（状态机会校验依赖是否完成、父任务是否可推进）；
- 该任务所需的工具可与本次 update 并发执行；
- 工具全部返回后再调用 update 将其设为 done；
- 阻塞的任务用 update(task_id, blocked, blockedReason) 标记，提供阻塞原因；
- 然后才能进入下一个任务。
状态机保证：同一时间只有一个叶子任务 in_progress；父子状态自动同步；verify 失败会返回可执行恢复路径。
所有任务都标记为 done/failed 后，必须调用 verify 校验通过，才能输出最终答案/总结。
禁止跳过更新、未 verify 通过时直接输出最终回复。
支持子任务：一个步骤可以拆分为多个子步骤。
计划会自动保存到虚拟文件系统 /scratch/plan.json（含 schemaVersion，跨版本兼容），跨轮次保持进度。
''';
