// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `tavily_search_tool`.
const String tavilySearchToolDescription = r'''
SearXNG 没找到理想结果时的备选搜索引擎。和 searxng_search 一样用法，换个角度再搜一次。有时候换个引擎就能找到不一样的答案。
'''
;
