// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `tool_search_tool`.
const String toolSearchToolDescription = r'''
你需要看看有哪些工具可以用、某个工具怎么用的时候用它。它会搜索已注册的所有工具，返回名字、描述和参数结构。就像翻开工具箱看看里面有什么。
'''
;
