// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `tool_search_tool`.
const String toolSearchToolDescription = r'''
当你需要某个不常用或不确定名称/参数的工具时，先用 tool_search 搜索。传入你想做的事（如"查询AI日报"、"企业ERP查询"），返回可用延迟工具列表，然后再用 defer_execute_tool 调用目标工具。不要凭猜测调用不确定的工具。
''';
