// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `weather_tool`.
const String weatherToolDescription = r'''
【必须】当用户询问任何城市的当前天气、气温、下雨、未来天气预报时调用此工具。禁止凭经验或训练数据猜测天气。
''';
