// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_tool_descriptions.dart

/// Tool description for `web_fetch_tool`.
const String webFetchToolDescription = r'''
你需要打开一个具体的网页、读一下上面写了什么的时候用它。比如搜索结果里有一条链接看起来很有用，就把它拿来读一读。会返回页面的文本内容。
'''
;
